#include <iostream>
#include <stdexcept>
using namespace std;

int main()
{
  
  throw std::logic_error("This logic error worked!");
  return(0);
}
